[test]
preload = "./happydom.ts"
coverage = true
coverageIgnoreSourcemaps = true   # default false
coverageSkipTestFiles = true       # default false
# to require 90% line-level and function-level coverage
# coverageThreshold = 0.9

# to set different thresholds for lines and functions
coverageThreshold = { line = 0.9, function = 0.9 }
